# fly.toml file generated for api-obitocourses on 2023-01-06T19:22:50+07:00

app = "api-obitocourses"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"

[build]
  [build.args]
    NODE_VERSION = "14"
    PHP_VERSION = "8.1"

[env]
  APP_ENV = "production"
  DB_CONNECTION = "pgsql"
  DB_HOST = "dbcourses.internal"
  DB_DATABASE= "courses"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
